import{a as M,S as w,i as l}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const S="28315893-0fd806bb9dd4884845b8c425c",v="https://pixabay.com/api/",$=15;async function f(r,t){return(await M(v,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:$}})).data}const m=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".js-loadMore");let q=new w(".gallery a",{captionsData:"alt"});function h(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:i,comments:L,downloads:b})=>`<li class="gallery-item">
  
        <a class="gallery-link" href="${a}">
        <img class="gallery-img" src="${s}" alt="${e}"/>
        </a>

       
        <ul class="gallery-socials-list">
            <li class="gallery-social-item"><span>Likes</span> ${o} </li>
            <li class="gallery-social-item"> <span>Views</span> ${i} </li>
            <li class="gallery-social-item"><span>Comments</span> ${L} </li>
            <li class="gallery-social-item"><span>Downloads</span> ${b} </li>
        </ul>
      </li>`).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}function P(){m.innerHTML=""}function j(){g.classList.add("loader")}function p(){g.classList.remove("loader")}function O(){y.classList.remove("js-loadMore")}function d(){y.classList.add("js-loadMore")}const R=document.querySelector(".form"),u=document.querySelector(".js-loadMore");p();R.addEventListener("submit",B);u.addEventListener("click",H);let c=1,n;async function B(r){if(r.preventDefault(),n=r.target.elements["search-text"].value.trim(),!n){l.warning({message:"Пустий рядок",position:"topRight"});return}P(),d(),j();try{const t=await f(n,c=1);if(t.hits.length>0){h(t.hits),O();const s=Math.ceil(t.totalHits/15);if(c>=s)return d(),l.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}else l.show({message:`Sorry, there are no images matching <br> your search "${n}". Please try again!`,color:"#ef4040",position:"topRight",messageColor:"#fafafb"})}catch(t){l.error({message:t.message,position:"topRight"})}finally{p(),r.target.reset()}}async function H(r){c++,u.disabled=!0;try{const t=await f(n,c);h(t.hits);const s=Math.ceil(t.totalHits/15);if(c>=s)return d(),l.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."});const e=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:e,left:0,behavior:"smooth"})}catch(t){console.log(t)}finally{u.disabled=!1}}
//# sourceMappingURL=index.js.map
