import{a as S,S as v,i}from"./assets/vendor-B5nsgUv9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const $="28315893-0fd806bb9dd4884845b8c425c",q="https://pixabay.com/api/",P=15;async function m(r,t){return(await S(q,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:P}})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".js-loadMore");let R=new v(".gallery a",{captionsData:"alt"});function h(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:M,downloads:w})=>`<li class="gallery-item">
  
        <a class="gallery-link" href="${a}">
        <img class="gallery-img" src="${s}" alt="${e}"/>
        </a>

       
        <ul class="gallery-socials-list">
            <li class="gallery-social-item"><span>Likes</span> ${o} </li>
            <li class="gallery-social-item"> <span>Views</span> ${n} </li>
            <li class="gallery-social-item"><span>Comments</span> ${M} </li>
            <li class="gallery-social-item"><span>Downloads</span> ${w} </li>
        </ul>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()}function O(){g.innerHTML=""}function L(){p.classList.add("loader")}function f(){p.classList.remove("loader")}function b(){y.classList.add("loadMore")}function d(){y.classList.remove("loadMore")}const B=document.querySelector(".form"),u=document.querySelector(".js-loadMore");f();B.addEventListener("submit",H);u.addEventListener("click",j);let l=1,c;async function H(r){if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),!c){i.warning({message:"Пустий рядок",position:"topRight"});return}O(),L(),d(),l=1;try{const t=await m(c,l);if(t.hits.length>0){h(t.hits),b();const s=Math.ceil(t.totalHits/15);if(l>=s)return d(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}else i.show({message:`Sorry, there are no images matching <br> your search "${c}". Please try again!`,color:"#ef4040",position:"topRight",messageColor:"#fafafb"})}catch(t){i.error({message:t.message,position:"topRight"})}finally{f(),r.target.reset()}}async function j(r){l++,u.disabled=!0,L(),d();try{const t=await m(c,l);h(t.hits),b();const s=Math.ceil(t.totalHits/15),a=document.querySelector(".gallery-item");if(!a)return;const e=a.getBoundingClientRect().height*2;if(window.scrollBy({top:e,left:0,behavior:"smooth"}),l>=s)return d(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(t){i.error({message:t.message,position:"topRight"})}finally{u.disabled=!1,f()}}
//# sourceMappingURL=index.js.map
